force-app/main/default/objects/Offering__c/Offering__c.object-meta.xml
<CustomObject>
    <label>Offering</label>
    <nameField>
        <label>Offering  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offering__c/fields/totalPrice__c.field-meta.xml
<CustomField>
    <fullName>totalPrice__c</fullName>
    <label>totalPrice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staffing__c/Staffing__c.object-meta.xml
<CustomObject>
    <label>Staffing</label>
    <nameField>
        <label>Staffing  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staffings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staffing__c/fields/Offering__c.field-meta.xml
<CustomField>
    <fullName>Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offering</label>
    <referenceTo>Offering__c</referenceTo>
    <relationshipLabel>Staffings</relationshipLabel>
    <relationshipName>Staffings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StaffingTriggerHandlerClass.cls
public class StaffingTriggerHandlerClass {
    public static void UpdateOfferTotalPriceFieldOnInsert(List<Staffing__c> newList){
        
        try{ 
             set<Id> offId = new set<Id>();
            for(Staffing__c Staffingob:newList){
                offId.add(Staffingob.Offering__c);
            }
 List<Offering__c> ofList = [Select Id,totalPrice__c from Offering__c where Id=:offId];
            for(Staffing__c ob: newList){
                 for(Offering__c offObj: ofList){
                     if(ob.Offering__c == offObj.id && ob.Price__c!=null){
                         if(offObj.totalPrice__c != null)
                          offObj.totalPrice__c += ob.Price__c;
                        // offObj.id = ob.Offering__c;
                         else
                             offObj.totalPrice__c = ob.Price__c;
                     }
                 }
            }
            update ofList;
        }Catch(Exception e){
            System.debug('Message'+e.getMessage());
            System.debug('LineNumber'+e.getLineNumber());
        }
    }
    public static void UpdateOfferTotalPriceFieldOnUpdate(List<Staffing__c> newList){
        try{ Set<Id> offId = new Set<Id>();
            for(Staffing__c ob: newList){
               offId.add(ob.Offering__c); 
            }           
     List<Offering__c> offList = [Select Id, totalPrice__c,(Select Id,Price__c from Staffings__r) from Offering__c where Id=:offId];   
            for(Offering__c offObj: offList){
                offObj.totalPrice__c = 0;
                for(Staffing__c staffObj:offObj.Staffings__r){
                    if(staffObj.Price__c!=null){                   
                     offObj.totalPrice__c += staffObj.Price__c;
                    }
                }
            }update offList;
            
        }  Catch(Exception e){
            System.debug('Message'+e.getMessage());
            System.debug('LineNumber'+e.getLineNumber());
        }
    }
}