force-app/main/default/objects/Favorite__c/Favorite__c.object-meta.xml
<CustomObject>
    <label>Favorite</label>
    <nameField>
        <label>Favorite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Favorite</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Favorite__c/fields/TestBusinessApplication__c.field-meta.xml
<CustomField>
    <fullName>TestBusinessApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TestBusinessApplication</label>
    <referenceTo>TestBusinessApplication__c</referenceTo>
    <relationshipLabel>Favorite</relationshipLabel>
    <relationshipName>Favorite</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestBusinessApplication__c/TestBusinessApplication__c.object-meta.xml
<CustomObject>
    <label>TestBusinessApplication</label>
    <nameField>
        <label>TestBusinessApplication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestBusinessApplications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BusinessApplicationEmailTemplate.cls
public class BusinessApplicationEmailTemplate {
    public static void EmailTemplate(){
        Favorite__c ba = [Select Id, TestBusinessApplication__r.Application__c,TestBusinessApplication__r.Email__c From Favorite__c where Id='a025j00000Cti0KAAR'];
 EmailTemplate et=[Select Id,Subject, Body from EmailTemplate where name ='CognizantTemplate'];
List<Messaging.SingleEmailMessage> Emailmsg = new List<Messaging.SingleEmailMessage>();
list<String> email= new list<String>();
email.add(ba.TestBusinessApplication__r.Email__c);
Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
msg.setTemplateId(et.Id);
msg.setWhatId(ba.Id);
msg.setTargetObjectId(Userinfo.getUserId());
msg.setTreatTargetObjectAsRecipient(false);        
msg.setToAddresses(email);
msg.setSaveAsActivity(false);
Emailmsg.add(msg);
Messaging.sendEmail(Emailmsg);





    }
}