force-app/main/default/objects/CompaniesProduct__c/CompaniesProduct__c.object-meta.xml
<CustomObject>
    <label>CompaniesProduct</label>
    <nameField>
        <label>CompaniesProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CompaniesProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CompaniesProduct__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CompaniesProducts</relationshipLabel>
    <relationshipName>CompaniesProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CompaniesProduct__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>ProductName</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactProduct.cls
public class ContactProduct {
    public static void ContactMethod(List<Contact> cList){
        try{
            //List<CompaniesProduct__c> proList = [Select Id,Contact__c From CompaniesProduct__c where Contact__c!=null];
            //List<Contact> conList = [Select Id,LastName,ProductName__c from contact];
              List<Contact> conList = new List<Contact>();
              Contact con = new Contact();
            con.FirstName = 'LCon';
            con.LastName = 'P';
            con.ProductName__c = 'p1,p2,p3';
            ConList.add(con);
            insert conList;
            List<CompaniesProduct__c> prList = new List<CompaniesProduct__c>();
            for(Contact c: cList){
                
            }
            
        }Catch(Exception e){
            System.debug('Message'+e.getMessage());
            System.debug('LineNumber'+e.getLineNumber());
        }
    }
}