force-app/main/default/objects/Modules__c/Modules__c.object-meta.xml
<CustomObject>
    <label>Modules</label>
    <nameField>
        <label>Modules Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modules__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Modules__c/fields/Trailhead_Data__c.field-meta.xml
<CustomField>
    <fullName>Trailhead_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trailhead Data</label>
    <referenceTo>Trailhead_Data__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trailhead_Data__c/Trailhead_Data__c.object-meta.xml
<CustomObject>
    <label>Trailhead Data</label>
    <nameField>
        <label>Trailhead Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailhead Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailhead_Data__c/fields/Module_Name__c.field-meta.xml
<CustomField>
    <fullName>Module_Name__c</fullName>
    <label>Module Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Asynch15.cls
public class Asynch15 implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('Select Id,Name,Status__c,Trailhead_Data__c From Modules__c Where Status__c =\'Completed\'');
    }
    public void execute(Database.BatchableContext bc, List<Modules__c> mList){
        
        List<Trailhead_Data__c> tList= [Select Id, Module_Name__c From Trailhead_Data__c];
        System.debug(mList);
        System.debug(tList);
        for(Modules__c m: mList){
            for(Trailhead_Data__c t: tList){
                if(m.Trailhead_Data__c==t.Id){
                     if(t.Module_Name__c == Null){
                        t.Module_Name__c = m.Name;
                    }
                    else{
                        t.Module_Name__c += m.Name;
                    }
                    
                }
            }
        } 
        update tList;
        
    } 
    public void finish(Database.BatchableContext bc){
        System.debug('Finish Function');
    }
    
}